### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by MiLaak** [GoogleCloudPlatform/node-red-contrib-google-cloud#53]
Hi,

I followed instructions from https://cloud.google.com/blog/products/application-development/using-node-red-with-google-cloud and created Compute Engine with node red container.

Then tested this example https://github.com/GoogleCloudPlatform/node-red-contrib-google-cloud/blob/master/examples/PubSub.json

I created pubsub topic and subscription for "test-topic" and added "owner" role for the service account of the VM where node red is running.

When deploying the node-red flow, both pubsub nodes in the flow gives error "Error: 7 PERMISSION_DENIED: Request had insufficient authentication scopes."

**Comment by MiLaak** [comment]
I got it working when tweaking many things. Including "Allow full access to all Cloud APIs" to VM and adding "Pub/Sub Admin" role to VMs service account.

**Comment by kolban-google** [comment]
Howdy @MiLaak .  Delighted to hear you got it working and thanks for taking the time to close the issue since it was resolved.  Just be sure that had you not found a resolution, we'd be here to try and support you.  If something in the future doesn't seem right, do what you did and post issues and we'll get to them quickly.
