### ISSUE TITLE
Procedure to use pubsub node in rasPi to send data to google cloud

### ISSUE THREAD

**Issue by sahebdatta** [GoogleCloudPlatform/node-red-contrib-google-cloud#64]
Hello,

I am very new to using google cloud. I am trying to establish communication between node-red (running on rasPi) and google cloud. I am now in a situation that says "Error: 7 PERMISSION_DENIED: User not authorized to perform this action."
I have generated and downloaded the key JSON file and mapped the content in the pubsub node, specified the topic, but no luck yet! Can you please help me sort out this issue?

Thanks in advance.

**Comment by libanj** [comment]
Hello @kolban-google, I actually got a similar issue, I am very new to this as well. In my GCP project, I have created a topic and a subscription to that same topic, In my NODE-RED flow, I am trying to use the pubsub push node so that I can publish telemetry data to the topic. I provided a service account key in the "Credential" field and I also filled in the "Topic" field, I did not fill in the "Key file" and the "Name" fields. When I click "Deploy", the pubsub node is trying to connect however it fails and it gives me this error:

Error: Unable to detect a Project Id in the current environment. 
To learn more about authentication and Google APIs, visit: 
https://cloud.google.com/docs/authentication/getting-started


I looked at the service account JSON key and it specified the project ID. I am pretty sure I am missing something however I'm not so sure.

If you could point me to the right direction that would be extremely helpful.

Thank you

**Comment by kolban-google** [comment]
Howdy ... I am here to help.  I don't know an immediate answer but I'll be delighted to work with you to assist.  Would you be willing to do a live screen share/chat with me via Google Meet?  If yes, either email me at kolban@google.com or instant message through Google Chat to kolban@google.com and we'll arrange a time.  I am in US Central Time time zone.
